version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB:-ETF}"
      MYSQL_USER: "${MYSQL_USER:-app}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-app123}"
      TZ: "${TZ:-Asia/Taipei}"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [my_network]

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on: [mysql]
    networks: [my_network]

networks:
  my_network:
    external: true

volumes:
  mysql_data:
